In [1]:
import pandas as pd
import numpy as np

In [2]:
#assume initial distribution is uniform
c=0.85
r0=np.array([0.2,0.2,0.2,0.2,0.2]).reshape(5,1)
r0

array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])

In [3]:
c=0.85
n=5
P=np.zeros((5,5))
P[0,1]=1
P[1,2]=0.5
P[1,3]=0.5
P[2,3]=1
P[3,0]=0.5
P[3,4]=0.5
P[4,2]=1
P

array([[0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0.5, 0. ],
       [0. , 0. , 0. , 1. , 0. ],
       [0.5, 0. , 0. , 0. , 0.5],
       [0. , 0. , 1. , 0. , 0. ]])

In [4]:
r_new= c*np.dot(np.transpose(P),r0)+(1-c)/n
for i in range(29):
    r_new=c*np.dot(np.transpose(P),r_new)+(1-c)/n

r_new

array([[0.15555492],
       [0.16223822],
       [0.23119216],
       [0.29545977],
       [0.15555492]])

In [5]:
np.round(r_new,4)

array([[0.1556],
       [0.1622],
       [0.2312],
       [0.2955],
       [0.1556]])